### ISSUE TITLE
output timestep

### ISSUE THREAD

**Issue by wanzhixiao** [hazdzz/STGCN#1]
i check your implementation of the last output ,there is a step that maps multi-steps to one.

do you think  Ko = T - len(blocks) * 2 * (Kt - 1) equal to   Ko -= len(blocks)*2 * (Ks - 1) ?

```
 def __init__(self, Kt, Ks, blocks, T, n_vertex, gnn, gcn_kernel, drop_prob):
        super(STGCN_GCN, self).__init__()
        self.st_block1 = STConvBlock(Kt, Ks, n_vertex, blocks[0], gnn, gcn_kernel, drop_prob)
        self.st_block2 = STConvBlock(Kt, Ks, n_vertex, blocks[1], gnn, gcn_kernel, drop_prob)
        Ko = T - len(blocks) * 2 * (Kt - 1)
        if Ko > 1:
            self.output = OutputLayer(blocks[-1][-1], Ko, n_vertex)
        else:
            raise ValueError(f'ERROR: kernel size Ko must be greater than 1, but received "{Ko}".')
```
and here is the orginal tensorflow version
```
    #Ko>0: kernel size of temporal convolution in the output layer.
    Ko = n_his
    # ST-Block
    #blocks [[1, 32, 64], [64, 32, 128]]
    for i, channels in enumerate(blocks):
        #?,8,228,64,  3,   3,
        x = st_conv_block(x, Ks, Kt, channels, i, keep_prob, act_func='GLU')
        Ko -= 2 * (Ks - 1)

    # Output Layer
    if Ko > 1:
        y = output_layer(x, Ko, 'output_layer')
    else:
        raise ValueError(f'ERROR: kernel size Ko must be greater than 1, but received "{Ko}".')
```

**Comment by hazdzz** [comment]
> i check your implementation of the last output ,there is a step that maps multi-steps to one.
> 
> 
> 
> do you think  Ko = T - len(blocks) * 2 * (Kt - 1) equal to   Ko -= len(blocks)*2 * (Ks - 1) ?
> 
> 
> 
> ```
> 
>  def __init__(self, Kt, Ks, blocks, T, n_vertex, gnn, gcn_kernel, drop_prob):
> 
>         super(STGCN_GCN, self).__init__()
> 
>         self.st_block1 = STConvBlock(Kt, Ks, n_vertex, blocks[0], gnn, gcn_kernel, drop_prob)
> 
>         self.st_block2 = STConvBlock(Kt, Ks, n_vertex, blocks[1], gnn, gcn_kernel, drop_prob)
> 
>         Ko = T - len(blocks) * 2 * (Kt - 1)
> 
>         if Ko > 1:
> 
>             self.output = OutputLayer(blocks[-1][-1], Ko, n_vertex)
> 
>         else:
> 
>             raise ValueError(f'ERROR: kernel size Ko must be greater than 1, but received "{Ko}".')
> 
> ```
> 
> and here is the orginal tensorflow version
> 
> ```
> 
>     #Ko>0: kernel size of temporal convolution in the output layer.
> 
>     Ko = n_his
> 
>     # ST-Block
> 
>     #blocks [[1, 32, 64], [64, 32, 128]]
> 
>     for i, channels in enumerate(blocks):
> 
>         #?,8,228,64,  3,   3,
> 
>         x = st_conv_block(x, Ks, Kt, channels, i, keep_prob, act_func='GLU')
> 
>         Ko -= 2 * (Ks - 1)
> 
> 
> 
>     # Output Layer
> 
>     if Ko > 1:
> 
>         y = output_layer(x, Ko, 'output_layer')
> 
>     else:
> 
>         raise ValueError(f'ERROR: kernel size Ko must be greater than 1, but received "{Ko}".')
> 
> ```

For the Chebyshev Polynomial Approximation, default value of Ks equals default value of Kt. For the Layer-Wise Linear, default value of Ks is 1, which does not equals to default value of Kt. The reason why I write Kt instead of Ks is that according to the paper the output v^{l+1} belongs to R^{(M-2(Kt-1))*n*C^{l+1}}. Because the author just implement the Chebyshev Polynomial Approximation, so Kt = Ks = 3, Ko = n_his - 2 * 2 * (Ks - 1) = n_his - 2 * 2 * (Kt - 1). However, I implemented both methods, so I write Ko = n_his - 2 * 2 * (Kt - 1).

**Comment by wanzhixiao** [comment]
thanks. i think this repository is a great pytorch version implementation of STGCN and will be popular. and i have another question, have you test your code in the dataset given by the origin paper,how is the effect?

**Comment by hazdzz** [comment]
> thanks. i think this repository is a great pytorch version implementation of STGCN and will be popular. and i have another question, have you test your code in the dataset given by the origin paper,how is the effect?

Not yet. But I'll will add the main function main_road_traffic.py for road traffic prediction.
