### ISSUE TITLE
ambiguous named variable

### ISSUE THREAD

**Issue by pengzhangzhi** [hazdzz/STGCN#13]
Hi，
thank you for open source the code. It is a great material for us to learn the detail of STGCN. However, when I was trying to read your code, I find some variables named ambiguously. It is really hard for me to understand it. 
For instance, in the data config  file:
`kt = 3` and `gamma = 0.999`. 
In the model.py, 
`def __init__(self, Kt, Ks,....`
You neither name those variable reasonably nor explain them with few lines of comments.
This repo regarding STGCN is the best one I found. I really want to learn the way you code deep learning algorithm by re-implement this repo. So please~
Thanks!

**Comment by hazdzz** [comment]
Please read the paper first, then read my code.
