### ISSUE TITLE
關於STGCN/data/train/road_traffic/裏數據集的問題

### ISSUE THREAD

**Issue by Hiccup-Horrendous-Haddock-I** [hazdzz/STGCN#15]
您好！
我從您的STGCN/data/train/road_traffic/裏下載了您提供的dataset，同時也從VeritasYin/STGCN_IJCAI-18裏面下載了原論文的dataset。我對比後發現，原論文的dataset中PeMS-M裏的V_228.csv和您的pemsd7-m中的vel.csv是完全一樣的，但是PeMS-M裏的W_228.csv和您的pemsd7-m中的adj_mat.csv就不一樣了（這兩份數據的行列個數都是相同的），而且您的adj_mat.csv中有非常多的0。請問一下這是為什麽呢？兩個文件之間的關系是什麽呢？

謝謝！

**Comment by hazdzz** [comment]
我有做稀疏化處理。

**Comment by Hiccup-Horrendous-Haddock-I** [comment]
> 我有做稀疏化處理。

那麽具體是怎麽處理的呢？有更具體一些的實操方法/代碼實現嗎？
謝謝！

**Comment by hazdzz** [comment]
README 上有寫。
