### ISSUE TITLE
TypeError: test() missing 1 required positional argument: 'test_iter'

### ISSUE THREAD

**Issue by benchoi93** [hazdzz/STGCN#17]
![image](https://user-images.githubusercontent.com/28798606/153448197-595eba89-a267-43e8-af5f-f6395ab83f05.png)

line 260 of stgcn.py should be

test(model_save_path, zscore, loss, model, test_iter)

![image](https://user-images.githubusercontent.com/28798606/153448238-332fe122-4a66-49d5-84a9-096589b31fb1.png)

**Comment by hazdzz** [comment]
Fixed.
