### ISSUE TITLE
intention of "class Align(nn.Module) "

### ISSUE THREAD

**Issue by jacobchen1** [hazdzz/STGCN#2]
Hey Hazdzz, thanks for your awesome work. I wonder why this "class Align(nn.Module):" has been applied into the module. What is the intention to use this class?

**Comment by hazdzz** [comment]
The purpose of class Align is aligning the input channel numbers and the output channel numbers. Although it is not mentioned in the paper, the author wrote it in his code. If you compare the code between author's and mine, you would find that I just abstract those three if conditional sentences from Temporal Convolution Layer and Spatial Convolution Layer to a class Align. That's it. As for why need to align the channel numbers, I strongly suggest you to ask author himself.
