### ISSUE TITLE
[Dataloader] 如何使用自定义数据集？

### ISSUE THREAD

**Issue by mokeeqian** [hazdzz/STGCN#20]
你好，我打算使用 ST-GCN 做时空序列预测，原始数据样本：
![image](https://github.com/hazdzz/STGCN/assets/45727636/0dd417f1-7b85-4e2a-87d9-518ddca6fd78)

问题建模是：
预测未来 N 个时间步长的区域的需求量

请问我该如何组织数据

**Comment by hazdzz** [comment]
你好，請你自己去問原作者。

**Comment by mokeeqian** [comment]
> 

好的，多有打扰！
