### ISSUE TITLE
训练时间激增问题

### ISSUE THREAD

**Issue by jiangjiang166** [hazdzz/STGCN#28]
作者你好啊，我想请教一下，我在进行前十几甚至几十轮的时候，代码运行速度都是很快的，大概17秒左右，但是会在第三十几或者第五十及轮的时候计算时间会激增，达到两小时甚至五小时，想问下这个问题是只有我一个人遇到还是普遍问题呢

**Comment by jiangjiang166** [comment]
代码的运行速度会在运行几十轮从一秒迭代50次左右变成30秒迭代一次

**Comment by hazdzz** [comment]
不清楚

**Comment by jiangjiang166** [comment]
不好意思，是我自己设备的问题，已经解决，给作者添麻烦了
