### ISSUE TITLE
Would you consider other dataset for future work?

### ISSUE THREAD

**Issue by jeongwhanchoi** [hazdzz/STGCN#4]
I'm struggling to use the dataset from the real-world problem.
Is there any breakthrough to use the dataset to the STGCN model? (even if additional node features)

Thank you

**Comment by hazdzz** [comment]
Of course, I have other datasets. However, I cannot share those datasets before my paper publishing.

**Comment by hazdzz** [comment]
I released two road traffic flow datasets from DCRNN on my GitHub repository.

**Comment by hazdzz** [comment]
I did it.

**Comment by hazdzz** [comment]
> I'm struggling to use the dataset from the real-world problem.
> Is there any breakthrough to use the dataset to the STGCN model? (even if additional node features)
> 
> Thank you

I did it.
