### ISSUE TITLE
Could you explain this constraint?

### ISSUE THREAD

**Issue by jeongwhanchoi** [hazdzz/STGCN#5]
https://github.com/hazdzz/STGCN/blob/17f6dd00d381dcf1edbd8bd3ff13f795501bb166/main_road_traffic.py#L89-L90

I'd like to use other datasets, but it seems to need to understand the `n_hist` argument.
I wonder about the relation among `n_hist`, `K_t` and etc.

**Comment by jeongwhanchoi** [comment]
I'm gonna use the dataset with the 60mins interval data. (cf. 5mins interval in PeMSD dataset)
How should I config the arguments in that dataset environment?

Thank you

**Comment by hazdzz** [comment]
> https://github.com/hazdzz/STGCN/blob/17f6dd00d381dcf1edbd8bd3ff13f795501bb166/main_road_traffic.py#L89-L90
> 
> 
> 
> I'd like to use other datasets, but it seems to need to understand the `n_hist` argument.
> 
> I wonder about the relation among `n_hist`, `K_t` and etc.

n_his must greater than n_pred. Kt means kernel number of temporal convolution. n_his means how many time intervals for training, n_pred means which one time interval the model should output. For example, n_his = 12, time intervals = 5 mins, n_pred = 3, that means give model 12 * 5 = 60 mins data, the model should output the next 3 * 5 = 15 mins data.

**Comment by hazdzz** [comment]
> I'm gonna use the dataset with the 60mins interval data. (cf. 5mins interval in PeMSD dataset)
> 
> How should I config the arguments in that dataset environment?
> 
> 
> 
> Thank you

You could refer to config files that I write for different dataset.

**Comment by jeongwhanchoi** [comment]
> > https://github.com/hazdzz/STGCN/blob/17f6dd00d381dcf1edbd8bd3ff13f795501bb166/main_road_traffic.py#L89-L90
> > 
> > I'd like to use other datasets, but it seems to need to understand the `n_hist` argument.
> > I wonder about the relation among `n_hist`, `K_t` and etc.
> 
> n_his must be greater than n_pred or equals to n_pred. Kt means kernel number of temporal convolution. n_his means how many time intervals for training, n_pred means which one time interval the model should output. For example, n_his = 12, time intervals = 5 mins, n_pred = 3, that means give model 12 * 5 = 60 mins data, the model should output the next 3 * 5 = 15 mins data.

Thank you for your explanation.
