### ISSUE TITLE
[question] Is there a way to use other feature data together?

### ISSUE THREAD

**Issue by jeongwhanchoi** [hazdzz/STGCN#6]
Is there a way to use feature data other than velocity data together?
I'd like to use other location features (e.g. landmark, the num of houses, etc.).

The STGCN models I know use only one feature for the speed of each node, but I would like to ask if there is any idea of using other information of the node as well.

Thank you.

**Comment by hazdzz** [comment]
Sorry, STGCN only accepts one-dimensional feature data. That's why I'm studying other spatio-temporal graph convolution neural network models.
