### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by fancyshun** [hazdzz/STGCN#7]
why your input shape is [32, 1, 12, 228],and author's input shape is [50, 21, 228, 1].I do not know why the rear three dimensions are different？

**Comment by hazdzz** [comment]
32 is the batch size, 1 is the feature dimension, 12 is the time steps for history, 228 is the node vertices. The STGCN author using the same way for data preprocessing, the DCRNN author have another thought for data preprocessing. If you are confused about data preprocessing from DCRNN, please ask the author of DCRNN.

**Comment by fancyshun** [comment]
you means your input and the author's input differ only in dimension.
Can I use the author's input through transpose the dimension as the input of your network？

**Comment by hazdzz** [comment]
> you means your input and the author's input differ only in dimension.
> 
> Can I use the author's input through transpose the dimension as the input of your network？

I don't understand what you mean.

**Comment by hazdzz** [comment]
I offered the data in my repository, you can use it. And I also wrote configuration files for training models.

**Comment by fancyshun** [comment]
do you know my mean？
I want to use the author's data processing in your model. however,your input is different from the author's. if I trans the input from [50,21,228,1] to [50,1,21,228]. I want to know whether this way is right. if it is wrong. how to deal with it.

**Comment by hazdzz** [comment]
> do you know my mean？
> 
> I want to use the author's data processing in your model. however,your input is different from the author's. if I trans the input from [50,21,228,1] to [50,1,21,228]. I want to know whether this way is right. if it is wrong. how to deal with it. 

Which author did you mean? STGCN's author or DCRNN's author?

**Comment by hazdzz** [comment]
> do you know my mean？
> I want to use the author's data processing in your model. however,your input is different from the author's. if I trans the input from [50,21,228,1] to [50,1,21,228]. I want to know whether this way is right. if it is wrong. how to deal with it.

And which dataset do you want to use? pemsd7-m, pems-bay or metr-la?

**Comment by hazdzz** [comment]
> do you know my mean？
> I want to use the author's data processing in your model. however,your input is different from the author's. if I trans the input from [50,21,228,1] to [50,1,21,228]. I want to know whether this way is right. if it is wrong. how to deal with it.

If you mean dataset pemsd7-m, you could use the data I offered in directory pemsd7-m.
