### ISSUE TITLE
question about the pemsd7-m data

### ISSUE THREAD

**Issue by michealowen** [hazdzz/STGCN#8]
There are two data files in pemsd7-m/. The first one vel.csv is the same as the STGCN's author's data named V_228.csv. But the adj_mat.csv is different. I want to konw how do u preprocess the raw data that the STGCN's author supplied in his repository. Thanks.

**Comment by hazdzz** [comment]
> There are two data files in pemsd7-m/. The first one vel.csv is the same as the STGCN's author's data named V_228.csv. But the adj_mat.csv is different. I want to konw how do u preprocess the raw data that the STGCN's author supplied in his repository. Thanks.

If you look closer to adj_mat.csv, you would know the relation between W_228.csv and adj_mat.csv.

**Comment by thomas10011** [comment]
> > There are two data files in pemsd7-m/. The first one vel.csv is the same as the STGCN's author's data named V_228.csv. But the adj_mat.csv is different. I want to konw how do u preprocess the raw data that the STGCN's author supplied in his repository. Thanks.
> 
> If you look closer to adj_mat.csv, you would know the relation between W_228.csv and adj_mat.csv. W_228.csv stores distance information, not weighted adjacency information. I fixed this, made the adj_mat.csv.

Hi, would you explain how did you compute the weighted matrix from W_228.cv? I am really confuse that your matrix is not satisfy its definition in the paper. Thus, I don't know why after I replacing the adj_mat.csv with my own weighted matrix, the code throws an error:
```
scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV. 
```

**Comment by hazdzz** [comment]
> > > There are two data files in pemsd7-m/. The first one vel.csv is the same as the STGCN's author's data named V_228.csv. But the adj_mat.csv is different. I want to konw how do u preprocess the raw data that the STGCN's author supplied in his repository. Thanks.
> > 
> > 
> > If you look closer to adj_mat.csv, you would know the relation between W_228.csv and adj_mat.csv. W_228.csv stores distance information, not weighted adjacency information. I fixed this, made the adj_mat.csv.
> 
> Hi, would you explain how did you compute the weighted matrix from W_228.cv? I am really confuse that your matrix is not satisfy its definition in the paper. Thus, I don't know why after I replacing the adj_mat.csv with my own weighted matrix, the code throws an error:
> 
> ```
> scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV. 
> ```

Do not use the formulation from STGCN paper(_Spatio-Temporal Graph Convolutional Networks: A Deep Learning Framework for Traffic Forecasting_). That's wrong! Using the formulation from ChebyNet paper_(Convolutional Neural Networks on Graphs with Fast Localized Spectral Filtering_).

**Comment by hazdzz** [comment]
> > > There are two data files in pemsd7-m/. The first one vel.csv is the same as the STGCN's author's data named V_228.csv. But the adj_mat.csv is different. I want to konw how do u preprocess the raw data that the STGCN's author supplied in his repository. Thanks.
> > 
> > 
> > If you look closer to adj_mat.csv, you would know the relation between W_228.csv and adj_mat.csv. W_228.csv stores distance information, not weighted adjacency information. I fixed this, made the adj_mat.csv.
> 
> Hi, would you explain how did you compute the weighted matrix from W_228.cv? I am really confuse that your matrix is not satisfy its definition in the paper. Thus, I don't know why after I replacing the adj_mat.csv with my own weighted matrix, the code throws an error:
> 
> ```
> scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV. 
> ```

This is the correct formulation as below:
<img width="1440" alt="Screen Shot 2021-04-04 at 01 48 32" src="https://user-images.githubusercontent.com/11409688/113486997-0f015080-94e8-11eb-9c06-46fb634de0a9.png">

**Comment by hazdzz** [comment]
If you wanna know more details about STGCN, please check this Chinese article as below:
https://zhuanlan.zhihu.com/p/286445515

**Comment by thomas10011** [comment]
> If you wanna know more details about STGCN, please check this Chinese article as below:
> https://zhuanlan.zhihu.com/p/286445515

谢谢您这么晚了还能及时回复我~我去看看

**Comment by thomas10011** [comment]
我还是有些疑惑，为什么对角元都为1？看了GCN的论文和代码，对角元不应该都是0嘛？

**Comment by hazdzz** [comment]
> 我还是有些疑惑，为什么对角元都为1？看了GCN的论文和代码，对角元不应该都是0嘛？

可以用 weight adjacency matrix 或 binary adjacency matrix 。前者，對角線是1，其餘皆是權重值；後者，對角線是0，兩個vertex相連，即為1。

**Comment by thomas10011** [comment]
emm，我查看了cnn_grah的代码，里面的计算权重矩阵的代码如下：
```
def adjacency(dist, idx):
    """Return the adjacency matrix of a kNN graph."""
    M, k = dist.shape
    assert M, k == idx.shape
    assert dist.min() >= 0

    # Weights.
    sigma2 = np.mean(dist[:, -1])**2
    dist = np.exp(- dist**2 / sigma2)

    # Weight matrix.
    I = np.arange(0, M).repeat(k)
    J = idx.reshape(M*k)
    V = dist.reshape(M*k)
    W = scipy.sparse.coo_matrix((V, (I, J)), shape=(M, M))

    # No self-connections.
    W.setdiag(0)

    # Non-directed graph.
    bigger = W.T > W
    W = W - W.multiply(bigger) + W.T.multiply(bigger)

    assert W.nnz % 2 == 0
    assert np.abs(W - W.T).mean() < 1e-10
    assert type(W) is scipy.sparse.csr.csr_matrix
    return W

```
作者是将图看作无自回路，所以对角元都设为0了？

**Comment by hazdzz** [comment]
> emm，我查看了cnn_grah的代码，里面的计算权重矩阵的代码如下：
> 
> ```
> 
> def adjacency(dist, idx):
> 
>     """Return the adjacency matrix of a kNN graph."""
> 
>     M, k = dist.shape
> 
>     assert M, k == idx.shape
> 
>     assert dist.min() >= 0
> 
> 
> 
>     # Weights.
> 
>     sigma2 = np.mean(dist[:, -1])**2
> 
>     dist = np.exp(- dist**2 / sigma2)
> 
> 
> 
>     # Weight matrix.
> 
>     I = np.arange(0, M).repeat(k)
> 
>     J = idx.reshape(M*k)
> 
>     V = dist.reshape(M*k)
> 
>     W = scipy.sparse.coo_matrix((V, (I, J)), shape=(M, M))
> 
> 
> 
>     # No self-connections.
> 
>     W.setdiag(0)
> 
> 
> 
>     # Non-directed graph.
> 
>     bigger = W.T > W
> 
>     W = W - W.multiply(bigger) + W.T.multiply(bigger)
> 
> 
> 
>     assert W.nnz % 2 == 0
> 
>     assert np.abs(W - W.T).mean() < 1e-10
> 
>     assert type(W) is scipy.sparse.csr.csr_matrix
> 
>     return W
> 
> 
> 
> ```
> 
> 作者是将图看作无自回路，所以对角元都设为0了？

這串代碼的出處是哪裡？

**Comment by thomas10011** [comment]
repository address: https://github.com/mdeff/cnn_graph
文件：lib/graph.py

**Comment by thomas10011** [comment]
并且关于他这段代码我还有一个不明白的地方，依照公式来看，sigma2应该是方差，但是作者的代码中sigma2直接用均值替代了。

**Comment by hazdzz** [comment]
> emm，我查看了cnn_grah的代码，里面的计算权重矩阵的代码如下：
> 
> ```
> 
> def adjacency(dist, idx):
> 
>     """Return the adjacency matrix of a kNN graph."""
> 
>     M, k = dist.shape
> 
>     assert M, k == idx.shape
> 
>     assert dist.min() >= 0
> 
> 
> 
>     # Weights.
> 
>     sigma2 = np.mean(dist[:, -1])**2
> 
>     dist = np.exp(- dist**2 / sigma2)
> 
> 
> 
>     # Weight matrix.
> 
>     I = np.arange(0, M).repeat(k)
> 
>     J = idx.reshape(M*k)
> 
>     V = dist.reshape(M*k)
> 
>     W = scipy.sparse.coo_matrix((V, (I, J)), shape=(M, M))
> 
> 
> 
>     # No self-connections.
> 
>     W.setdiag(0)
> 
> 
> 
>     # Non-directed graph.
> 
>     bigger = W.T > W
> 
>     W = W - W.multiply(bigger) + W.T.multiply(bigger)
> 
> 
> 
>     assert W.nnz % 2 == 0
> 
>     assert np.abs(W - W.T).mean() < 1e-10
> 
>     assert type(W) is scipy.sparse.csr.csr_matrix
> 
>     return W
> 
> 
> 
> ```
> 
> 作者是将图看作无自回路，所以对角元都设为0了？

你可以參考他的代碼。我自己試驗過對角線是0或1，都不影響實驗結果。

**Comment by hazdzz** [comment]
> 并且关于他这段代码我还有一个不明白的地方，依照公式来看，sigma2应该是方差，但是作者的代码中sigma2直接用均值替代了。

反正我公式給你了，要怎麼寫代碼，你自己選擇。

**Comment by thomas10011** [comment]
好，多谢指教

**Comment by michealowen** [comment]
> > There are two data files in pemsd7-m/. The first one vel.csv is the same as the STGCN's author's data named V_228.csv. But the adj_mat.csv is different. I want to konw how do u preprocess the raw data that the STGCN's author supplied in his repository. Thanks.
> 
> If you look closer to adj_mat.csv, you would know the relation between W_228.csv and adj_mat.csv. W_228.csv stores distance information, not weighted adjacency information. I fixed this, made the adj_mat.csv.

OK I see, thanks for your reply!!

**Comment by xeroCBW** [comment]
你好，想问下pemsd7-m这里K(threshold)取值是多少啊？想自己动手试下。

**Comment by hazdzz** [comment]
> 

詳見原論文。請你自己去看論文。

**Comment by hazdzz** [comment]
> 你好，想问下pemsd7-m这里K(threshold)取值是多少啊？想自己动手试下。

詳見原論文。請你自己去看論文。

**Comment by xeroCBW** [comment]
![Snip20230222_15](https://user-images.githubusercontent.com/14839269/220655018-0b44ce72-0193-40be-9c01-7c6aadc1c557.png)
![image](https://user-images.githubusercontent.com/14839269/220656004-af81c682-0a37-4918-9b4f-0e5b799af80f.png)

论文k(epsilon)=0.5,但是 adj.npz好像不是

**Comment by hazdzz** [comment]
> ![Snip20230222_15](https://user-images.githubusercontent.com/14839269/220655018-0b44ce72-0193-40be-9c01-7c6aadc1c557.png)

我是直接用原作者提供的 data，如果與論文不符，請你諮詢原作者。

**Comment by xeroCBW** [comment]
好的好的，感谢

**Comment by xeroCBW** [comment]
> > ![Snip20230222_15](https://user-images.githubusercontent.com/14839269/220655018-0b44ce72-0193-40be-9c01-7c6aadc1c557.png)
> 
> 我是直接用原作者提供的 data，如果與論文不符，請你諮詢原作者。

补充下，这里使用k=0.1好像就能跟adj.npz对上

**Comment by hazdzz** [comment]
> > > ![Snip20230222_15](https://user-images.githubusercontent.com/14839269/220655018-0b44ce72-0193-40be-9c01-7c6aadc1c557.png)
> > 
> > 
> > 我是直接用原作者提供的 data，如果與論文不符，請你諮詢原作者。
> 
> 补充下，这里使用k=0.1好像就能跟adj.npz对上

感謝你的建議。
