### ISSUE TITLE
Can u achieve the claimed MAE/RMSE of the STGCN paper?

### ISSUE THREAD

**Issue by michealowen** [hazdzz/STGCN#9]
I use the pytorch implementation of repo https://github.com/FelixOpolka/STGCN-PyTorch.git to train on PEMSD7-M, but i can not achieve similar result.

**Comment by hazdzz** [comment]
> I use the pytorch implementation of repo https://github.com/FelixOpolka/STGCN-PyTorch.git to train on PEMSD7-M, but i can not achieve similar result.

You don't need to. The code of the author is wrong, so made other third parties' code wrong either. I fixed the code totally. You can see the result from the correct code is very good.

**Comment by michealowen** [comment]
> > I use the pytorch implementation of repo https://github.com/FelixOpolka/STGCN-PyTorch.git to train on PEMSD7-M, but i can not achieve similar result.
> 
> You don't need to. The author's code is wrong, so made other third parties' code wrong either. I fixed the code totally. You can see the result from the correct code is very good.

Thank you, I will have a try.
